import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const db = new Database(path.join(__dirname, 'data', 'freeapi.db'));
const cols = db.prepare('PRAGMA table_info(settings)').all();
console.log(JSON.stringify(cols, null, 2));
const all = db.prepare('SELECT * FROM settings').all();
console.log(JSON.stringify(all, null, 2));
db.close();
